version: '3.4'

networks:
  minimal-api:

services:
  
  minimal-api.api:
    # image: sebastiansuarez01/minimal-api:latest
    image: sebastiansuarez01/minimal-api:v5
    container_name: minimalapi
    build:
      context: .
      dockerfile: /Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
      - ASPNETCORE_HTTPS_PORTS=5001
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - minimal-api.postgres.db
      - minimal-api.cache.redis
    networks:
      - minimal-api
  
  minimal-api.postgres.db:
    image: postgres:16
    container_name: minimalapi.db
    environment:
      POSTGRES_USER: "minimalapi"
      POSTGRES_PASSWORD: "minimalapi"
      POSTGRES_DB: "minimalapi_db"
    volumes:
      - ./.containers/minimalapi-db:/var/lib/postgresql/data
    networks:
      - minimal-api
  
  minimal-api.cache.redis:
    image: redis:7
    container_name: minimal-api.cache
    ports:
      - 6379:6379
    networks:
      - minimal-api
  