version: '3.4'

networks:
  minimal-api:

services:
  
  minimal-api.api:
    image: sebastiansuarez01/minimal-api:latest
    container_name: minimalapi
#    build:
#      context: .
#      dockerfile: Minimal-API.API/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
      - ASPNETCORE_HTTPS_PORTS=5001
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - minimal-api.postgres.db
    networks:
      - minimal-api
  
  
  minimal-api.postgres.db:
    image: postgres:latest
    container_name: minimalapi.db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "minimalapi"
      POSTGRES_PASSWORD: "minimalapi"
      POSTGRES_DB: "minimalapi_db"
    volumes:
      - ./.containers/minimalapi-db:/var/lib/postgresql/data
    networks:
      - minimal-api