#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: webapp-deployment
#  labels:
#    app: webapp
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: webapp
#  template:
#    metadata:
#      labels:
#        app: webapp
#        app.kubernetes.io/name: webapp
#        env: dev
#    spec:
#      containers:
#        - name: webapp-api
#          image: sebastiansuarez01/minimal-api:v3
#          ports:
#            - containerPort: 5000
#              name: http-web-api
#          resources:
#            requests:
#              cpu: 100m
#              memory: 100Mi
#            limits:
#              cpu: 500m
#              memory: 500Mi
#          env:
#            - name: ASPNETCORE_URLS
#              value: "http://+:5000"
#            - name: ASPNETCORE_ENVIRONMENT
#              value: "Development"
#            - name: ASPNETCORE_HTTP_PORTS
#              value: "5000"
#            - name: ASPNETCORE_HTTPS_PORTS
#              value: "5001"
#            - name: POSTGRES_USER
#              valueFrom:
#                secretKeyRef:
#                  name: postgres-secret
#                  key: postgres_user
#            - name: POSTGRES_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  name: postgres-secret
#                  key: postgres_password
#            - name: POSTGRES_DB
#              valueFrom:
#                secretKeyRef:
#                  name: postgres-secret
#                  key: postgres_db
#            - name: DB_URL
#              valueFrom:
#                configMapKeyRef:
#                  name: postgres-config
#                  key: postgres_url
#            - name: REDIS_URL
#              valueFrom:
#                configMapKeyRef:
#                  name: redis-config
#                  key: redis_url

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: sebastiansuarez01/minimal-api:v5
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_DB 
              value: "postgres-db"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: HOST
              value: "postgresdb"
            - name: PORT
              value: "5432"
            - name: ASPNETCORE_URLS
              value: "http://+:5000"
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ASPNETCORE_HTTP_PORTS
              value: "5000"
            - name: ASPNETCORE_HTTPS_PORTS
              value: "5001"
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_PORT
              value: "6379"

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
